sudo : required
services:
        - docker
before_install:
        - docker build -t novperez/docker-react -f Dockerfile.dev .
script:
        docker run novperetz/docker-react npm run test -- --coverage

