sudo : required
services:
        - docker
before_install:
        - docker build -t november21/docker-react -f Dockerfile.dev .
script:
        - docker run november21/docker-react npm run test -- --coverage

